#                                         https://docs.docker.com/compose/compose-file/
# Cuando ejecutamos los comandos:
# make | make up | make start | docker-compose up...
# Hacemos que docker-compose cargue y ejecute este archivo el cual contiene los servicios que queremos desplegar en DIFERENTES contenedores
# Para ver infomarción sobre los contenedor que tenemos actualmente podemos ejecutar el comando "docker ps -a"

version: '3.7'

services:

  httpd:
    image: httpd:2.4-alpine #Imagen base de la que partimos
    container_name: "docker_compose_tutorial_alpine_httpd" # Cuando hagamos el docker-compose up se creara un contenedor y este sera su nombre
    working_dir: /usr/local/apache2/htdocs
    volumes: # Vinculacion de carpetas Carpeta_Real:Carpeta_Container
      - ./public_html:/usr/local/apache2/htdocs:cached
    ports: #Mapeamos puertos Puerto_Real:Puerto_Container
      - "80:80"


  mysql:
    image: mysql:5.7
    container_name: "docker_compose_tutorial_mysql-5.7"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./Databases:/var/lib/mysql #Con este volumen hacemos persistentes los datos que insertemos en la BD
    restart: always
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080